name = "SeisDetective"
uuid = "fefaf115-fdb9-440b-826d-0e78e901b1e3"
authors = ["Tim Clements <tclements@usgs.gov> and contributors"]
version = "0.1.0"

[deps]
SeisIO = "b372bb87-02dd-52bb-bcf6-c30dd83fd342"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
SeisIO = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
